### ISSUE TITLE
Can't bind SUB socket on erlangzmq

### ISSUE THREAD

**Issue by jchassoul** [chovencorp/erlangzmq#1]
Hi there, I'm trying to bind on SUB with erlangzmq but I got some errors.

The following python code bind a SUB socket that multiple PUB end-points can use to publish messages; SUB bind, PUB connect.

https://gist.github.com/jchassoul/de134b888115e448f3b96180553a9278

But, trying to reproduce the same behavior with erlangzmq I got some errors and can't make it work, this is the example code that I'm using and the error attached at the end of the file.

https://gist.github.com/jchassoul/408ede693760bcca44c84688e37c2777

I have some production code on python that bind on SUB and multiple PUB's send messages to different topics, I really want to move that code from python to erlang, erlangzmq was love at first sight.

**Comment by drozzy** [comment]
Thank you for submitting this issue.

Please try using `connect` on the client, and `bind` on the server.

I still think it should work the other way around, but let me dig into this some more.

**Comment by drozzy** [comment]
Alas, since erlangzmq only supports NULL security mechanism, for now at least, bind means server, and connect means client:

> The peer that binds SHALL be the server, and connecting peer SHALL be the client.

 See "The NULL Security Mechanism" of the spec: http://rfc.zeromq.org/spec:37/ZMTP

Closing this for now. Let me know if it doesn't work the other way around.

**Comment by jchassoul** [comment]
I think we're kind of talking about different things, in my case the server the socket that bind its a SUB type socket and I have different machines connecting with a PUB socket that use connect, they send messages to the server using different topics, so it is not a security issue.

In theory with ZeroMQ sockets, it does not matter which end connects and which end binds, in this case it's a network design issue not a security matter, this pattern is really not that uncommon ("bind the SUB socket a connect the PUB") it is used for example to get logs from different boxes and send those messages to a logging server that use bind on SUB.

On the first gits that I provide you can see a little example running on python, I can also set that network topology using other languages and zeromq but for some reason it crash with erlangzmq.

**Comment by jchassoul** [comment]
Currently the problem is using a SUB socket with bind on erlangzmq, I can for example use a erlangzmq PUB socket and connect it to the machine that bind the SUB socket, but just if I use another language and zmq library to bind the SUB.

I can't reproduce the same behavior just with erlangzmq, I can't bind on SUB with erlangzmq, but I can and always have been able to do it on other zmq libraries using other languages, that's why I open the issue because I could be wrong but I think it is something on erlangzmq not a network or security issue.

I really like erlangzmq the quality of the code is impressive it's the most awesome zmq driver for erlang that I have come across, but unfortunately I can't use it properly for all my use cases if I can't bind the SUB socket.

**Comment by jchassoul** [comment]
On the second gist I provide the erlang code that I'm running for test this message pattern, I do bind the server and connect the client as you suggest from the start on the original issue report, I also can help with any other tests if required. (=

**Comment by drozzy** [comment]
Oh Ok, I think I misunderstood the issue. You're saying that erlang to erlang works but not Python to erlang? Let me look into this some more.

P.S. By the way, if you spot something you want to work differently feel free to submit a pull request.

**Comment by drozzy** [comment]
No idea how to fix this yet.

**Comment by drozzy** [comment]
Ok, it seems like the issue is that you are not waiting long enough for PUB and SUB sockets to negotiate a connection. It is misinterpreting the "subscription" request as an answer to a handshake.

Try waiting a second on each end before sending messages. If you notice this is the "hack" that is used in the guide: http://zguide.zeromq.org/py:pathopub

If you want to make sure it always works, consider creating a separate socket pair (req-rep) where you signal that both sends are ready.

Here is what worked for me:

SHELL1:

    {ok, Socket} = erlangzmq:socket(sub).
    erlangzmq:bind(Socket, tcp, "localhost", 5555).
    erlangzmq:subscribe(Socket, <<"H ">>).
    
SHELL2:

    {ok, Socket} = erlangzmq:socket(pub).
    erlangzmq:connect(Socket, tcp, "localhost", 5555).

Now the two endpoints had a chance to connect.

SHELL1:

    erlangzmq:recv(Socket).

SHELL 2

    erlangzmq:send(Socket, <<"NOPE">>).
    erlangzmq:send(Socket, <<"H ", "YES">>).

and in SHELL 1 you should see:

    {ok, <<"H YES>>).

Let me know if this works for you!

**Comment by drozzy** [comment]
This should be working now in 1.1.0.

Thanks a bunch! This was a tricky one.

**Comment by jchassoul** [comment]
This is awesome!!! thanks from the bottom of my heart, your work is impressive.
