### ISSUE TITLE
Add this library to hex.pm

### ISSUE THREAD

**Issue by pedrosnk** [chovencorp/erlangzmq#2]
Please, can you add this library to https://hex.pm . It you'd facilitate a lot its use withing mix and rebar3 with rebar3_hex plugin.

**Comment by drozzy** [comment]
As soon as I figure out why my hex plugin doesn't work:
https://github.com/hexpm/rebar3_hex/issues/53

**Comment by drozzy** [comment]
Added. Let me know if you can pull it down through hex successfully.

**Comment by pedrosnk** [comment]
It works nice, thanks very much :D
